server {
  listen 6722;

  root /home/pi/iot-sr201;

  index index.html;

  location ~* \.php {
    try_files $uri =404;
    fastcgi_pass   unix:/var/run/php-fpm.sock;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
  }

	location /images/random/ {
		proxy_pass https://source.unsplash.com/random/;
		proxy_redirect default;
		proxy_ssl_server_name on;
		proxy_ssl_verify off;
	}

	location /images/bitcoin {
		proxy_pass https://source.unsplash.com/random?bitcoin;
		proxy_ssl_server_name on;
		proxy_ssl_verify off;
	}

	access_log /var/log/nginx/pump.log;
}
